<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>de.adito.picoservice</groupId>
    <artifactId>picoservice-parent</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>picoservice-integration-tests</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>de.adito.picoservice</groupId>
      <artifactId>picoservice-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>de.adito.picoservice</groupId>
      <artifactId>picoservice-processor</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.11.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <proc>full</proc>
          <!-- We want to test the autodiscovery instead of the recommended, explicit annotationProcessor-configuration here  -->
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
