<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>de.adito.picoservice</groupId>
    <artifactId>picoservice-parent</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>picoservice-integration-tests</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>

  <properties>
    <!-- This module exists only to run integration tests and is never released. -->
    <maven.install.skip>true</maven.install.skip>
    <maven.deploy.skip>true</maven.deploy.skip>
    <maven.source.skip>true</maven.source.skip>
    <maven.javadoc.skip>true</maven.javadoc.skip>
    <gpg.skip>true</gpg.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>de.adito.picoservice</groupId>
      <artifactId>picoservice-core</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>de.adito.picoservice</groupId>
      <artifactId>picoservice-processor</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.11.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <configuration>
          <!-- flatten here has no benefit, so lets skip it -->
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <!-- no jar required for the integration tests -->
          <execution>
            <id>default-jar</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <executions>
          <execution>
            <id>default-testCompile</id>
            <configuration>
              <!-- testing the autodiscovery rather than explicit annotation-processor configuration here -->
              <jdkToolchain>
                <version>25</version>
              </jdkToolchain>
              <proc>full</proc>
              <release>25</release>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
