<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>de.adito.picoservice</groupId>
  <artifactId>picoservice-parent</artifactId>
  <version>2.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>A minimalist registry for Java services using ServiceLoader</description>
  <url>https://github.com/aditosoftware/picoservice</url>

  <modules>
    <module>picoservice-core</module>
    <module>picoservice-processor</module>
    <!--  picoservice is a compatibility module that contains core and processor like the 1.x.x-version of picoservices  -->
    <module>picoservice</module>
    <module>picoservice-integration-tests</module>
  </modules>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>LICENSE.md</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>jboesl</id>
      <name>Johannes Boesl</name>
      <email>j.boesl@adito.de</email>
      <timezone>1</timezone>
      <organization>ADITO Software GmbH</organization>
      <organizationUrl>https://www.adito.de</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git@github.com:aditosoftware/picoservice.git</connection>
    <developerConnection>scm:git:git@github.com:aditosoftware/picoservice.git</developerConnection>
    <url>git@github.com:aditosoftware/picoservice.git</url>
  </scm>

  <issueManagement>
    <url>https://github.com/aditosoftware/picoservice/issues</url>
    <system>github</system>
  </issueManagement>

  <properties>
    <maven.compiler.release>8</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.5.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.5.5</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.5.1</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.4</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.4</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>3.6.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-source-plugin</artifactId>
          <version>3.4.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>3.2.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>3.0.1</version>
        </plugin>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>0.8.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <proc>none</proc>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>release</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-source-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-javadoc-plugin</artifactId>
            <configuration>
              <additionalJOption>-Xdoclint:none</additionalJOption>
              <jdkToolchain>
                <version>11</version>
              </jdkToolchain>
              <source>8</source>
            </configuration>
            <executions>
              <execution>
                <id>attach-javadoc</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <publishingServerId>maven-central-repository</publishingServerId>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>snapshot</id>
      <distributionManagement>
        <repository>
          <id>adito.m2</id>
          <name>releases</name>
          <url>${repository.releases}</url>
        </repository>
        <snapshotRepository>
          <id>adito.m2</id>
          <name>snapshots</name>
          <url>${repository.snapshots}</url>
          <uniqueVersion>false</uniqueVersion>
        </snapshotRepository>
      </distributionManagement>
    </profile>
  </profiles>
</project>
