package de.adito.picoservice.processor;

import de.adito.picoservice.PicoService;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.*;
import java.io.*;
import java.lang.annotation.*;
import java.nio.file.*;
import java.text.MessageFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Generates instances of {@link de.adito.picoservice.IPicoRegistration} and the corresponding service entries in the
 * META-INF directory for classes annotated with annotations that are annotated with {@link de.adito.picoservice.PicoService}.
 *
 * @author j.boesl, 23.03.15
 */
@SupportedAnnotationTypes("*")
public class AnnotationProcessorPico extends AbstractProcessor
{
  private static final String PICO_POSTFIX = "PicoService";
  private static final String CLASS_HASH = String.valueOf(AnnotationProcessorPico.class.hashCode());
  private static final String REGISTRATION_TEMPLATE = "package {0};\n" +
      "\n" +
      "import de.adito.picoservice.IPicoRegistration;\n" +
      "\n" +
      "import {4};\n" +
      "\n" +
      "@Generated(value = \"de.adito.picoservice.processor.AnnotationProcessorPico\", date = \"{3}\", comments = \"hash:{5}\")\n" +
      "public class {1} implements IPicoRegistration\n" +
      "'{'\n" +
      "  @Override\n" +
      "  public Class<?> getAnnotatedClass()\n" +
      "  '{'\n" +
      "    return {2}.class;\n" +
      "  '}'\n" +
      "'}'";
  private static final String SERVICE_REGISTRATION_PATH = "META-INF/services/de.adito.picoservice.IPicoRegistration";
  private final Set<TypeElement> processedElements = new HashSet<>();
  private final Set<String> generatedServices = new LinkedHashSet<>();

  private static boolean _isSupportedEnclosingElement(Element pElement)
  {
    // The semantic ElementKind predicates keep this Java 8-compiled processor forward compatible:
    // isClass() covers classes, enums and records, while
    // isInterface() also covers annotation types
    // Executable and local contexts remain unsupported because generated top-level classes cannot reference them
    ElementKind kind = pElement.getKind();
    return kind == ElementKind.PACKAGE || kind.isClass() || kind.isInterface();
  }

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv)
  {
    Set<TypeElement> annotatedElements = new LinkedHashSet<>();
    for (TypeElement annotation : annotations)
    {
      if (annotation.getAnnotation(PicoService.class) != null)
      {
        if (_isValidElement(annotation))
          for (Element annotatedElement : roundEnv.getElementsAnnotatedWith(annotation))
          {
            if (processedElements.add((TypeElement) annotatedElement))
              annotatedElements.add((TypeElement) annotatedElement);
          }
      }
    }
    if (!annotatedElements.isEmpty())
      _generateRegistrations(annotatedElements);
    if (roundEnv.processingOver() && !generatedServices.isEmpty())
      _writeServiceRegistration();

    return false;
  }

  private void _generateRegistrations(Set<TypeElement> pAnnotatedElements)
  {
    // abort early if the required @Generated annotation is unavailable, as registration classes cannot be created without it
    String generatedAnnotationImport = _getGeneratedAnnotationImport();
    if (generatedAnnotationImport == null)
      return;

    Filer filer = processingEnv.getFiler();
    for (TypeElement typeElement : pAnnotatedElements)
    {
      try
      {
        _ElementInfo eI = new _ElementInfo(typeElement, processingEnv.getMessager());
        eI.write(filer, generatedAnnotationImport);
        generatedServices.add(eI.fqn);
      }
      catch (IOException e)
      {
        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, e.getLocalizedMessage(), typeElement);
      }
    }
  }

  /**
   * Creates the service definition once all annotation-processing rounds have completed.
   * This allows registrations generated by other processors in later rounds to be included.
   */
  private void _writeServiceRegistration()
  {
    Set<String> serviceSet = new LinkedHashSet<>(generatedServices);
    Filer filer = processingEnv.getFiler();
    try
    {
      FileObject serviceFile = filer.getResource(StandardLocation.CLASS_OUTPUT, "", SERVICE_REGISTRATION_PATH);
      if (Files.isRegularFile(Paths.get(serviceFile.toUri())))
      {
        try (BufferedReader reader = new BufferedReader(serviceFile.openReader(true)))
        {
          String line;
          while ((line = reader.readLine()) != null)
            serviceSet.add(line);
        }
      }
    }
    catch (IOException e)
    {
      StringWriter exceptionDetails = new StringWriter();
      e.printStackTrace(new PrintWriter(exceptionDetails));
      processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Could not load existing serviceSet:\n" + exceptionDetails);
    }

    try
    {
      List<String> services = new ArrayList<>(serviceSet);
      Collections.sort(services);
      FileObject serviceFile = filer.createResource(StandardLocation.CLASS_OUTPUT, "", SERVICE_REGISTRATION_PATH);
      try (Writer writer = serviceFile.openWriter())
      {
        for (String service : services)
          writer.append(service).append("\n");
      }
    }
    catch (IOException x)
    {
      processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Failed to write service definition files: " + x);
    }
  }

  private String _getGeneratedAnnotationImport()
  {
    if (processingEnv.getElementUtils().getTypeElement("javax.annotation.processing.Generated") != null)
      return "javax.annotation.processing.Generated";
    if (processingEnv.getElementUtils().getTypeElement("javax.annotation.Generated") != null)
      return "javax.annotation.Generated";

    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
        "Cannot generate pico registrations: neither javax.annotation.processing.Generated nor javax.annotation.Generated is available");
    return null;
  }

  private boolean _isValidElement(Element pElement)
  {
    Retention retention = pElement.getAnnotation(Retention.class);
    if (retention == null || retention.value() != RetentionPolicy.RUNTIME)
    {
      processingEnv.getMessager().printMessage(Diagnostic.Kind.MANDATORY_WARNING, "Retention should be RUNTIME", pElement);
      return false;
    }
    Target target = pElement.getAnnotation(Target.class);
    if (target == null || target.value().length == 0)
    {
      processingEnv.getMessager().printMessage(Diagnostic.Kind.MANDATORY_WARNING, "Target has to be defined", pElement);
      return false;
    }
    else
    {
      for (ElementType elementType : target.value())
      {
        if (elementType != ElementType.TYPE)
        {
          processingEnv.getMessager().printMessage(Diagnostic.Kind.MANDATORY_WARNING, "Unsupported type: " + elementType, pElement);
          return false;
        }
      }
    }
    return true;
  }

  @Override
  public SourceVersion getSupportedSourceVersion()
  {
    return SourceVersion.latestSupported();
  }

  /**
   * Bag for element info.
   */
  private static class _ElementInfo
  {
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mmZ");

    private final TypeElement typeElement;
    private final String pckg;
    private final String annotatedClsName;
    private final String clsName;
    private final String fqn;
    private final Messager processingEnvMessager;

    _ElementInfo(TypeElement pTypeElement, Messager pProcessingEnvMessager)
    {
      typeElement = pTypeElement;
      processingEnvMessager = Objects.requireNonNull(pProcessingEnvMessager);

      pckg = _getPackage(pTypeElement);
      annotatedClsName = _getAnnotatedClassName(pTypeElement);
      clsName = annotatedClsName.replaceAll("\\.", "\\$") + PICO_POSTFIX;
      fqn = pckg + "." + clsName;
    }

    void write(Filer pFiler, String pGeneratedAnnotationImport) throws IOException
    {
      try (Writer writer = pFiler.createSourceFile(fqn, typeElement).openWriter())
      {
        // dynamic build values (date and hash) are intentionally included for human identification purposes
        String date = OffsetDateTime.now(ZoneOffset.UTC).format(DATE_FORMATTER);
        String content = MessageFormat.format(REGISTRATION_TEMPLATE, pckg, clsName, annotatedClsName, date, pGeneratedAnnotationImport, CLASS_HASH);
        writer.write(content);
      }
    }

    private String _getPackage(Element pElement)
    {
      Element element = pElement;
      while (element != null)
      {
        if (element.getKind() == ElementKind.PACKAGE)
        {
          // fix for https://github.com/aditosoftware/picoservice/issues/3
          if (element instanceof QualifiedNameable)
            return ((QualifiedNameable) element).getQualifiedName().toString();
          return element.toString();
        }
        Element enclosingElement = element.getEnclosingElement();
        if (_isSupportedEnclosingElement(enclosingElement))
          element = enclosingElement;
        else
        {
          processingEnvMessager.printMessage(Diagnostic.Kind.ERROR, "Element type not supported", pElement);
          break;
        }
      }
      return "";
    }

    private String _getAnnotatedClassName(Element pElement)
    {
      StringBuilder name = new StringBuilder();
      Element element = pElement;
      while (element != null && element.getKind() != ElementKind.PACKAGE)
      {
        if (name.length() > 0)
          name.insert(0, ".");
        name.insert(0, element.getSimpleName());
        Element enclosingElement = element.getEnclosingElement();
        if (_isSupportedEnclosingElement(enclosingElement))
          element = enclosingElement;
        else
        {
          processingEnvMessager.printMessage(Diagnostic.Kind.ERROR, "Element type not supported", pElement);
          break;
        }
      }
      return name.toString();
    }
  }

}
