package de.adito.picoservice;

import javax.annotation.Nonnull;

/**
 * Mini service class for java's {@link java.util.ServiceLoader}. Instances of this are generated by
 * {@link de.adito.picoservice.processor.AnnotationProcessorPico} at compile time.
 *
 * @author j.boesl, 23.03.15
 */
public interface IPicoRegistration
{
  /**
   * Needed to resolve the service class.
   *
   * @return the annotated class.
   */
  @Nonnull
  Class<?> getAnnotatedClass();
}
